const LAT=40.4168,LON=-3.7038,$=id=>document.getElementById(id);const actions={Normal:'Keep monitoring; no new action',Watch:'Check data with Canal de Isabel II; prepare public communications',Alert:'Launch water-saving campaign; reduce potable water used for park irrigation and street cleaning; increase use of reclaimed water where possible',Emergency:'Recommend that the regional authorities consider stronger restrictions; activate an emergency communication and municipal conservation plan'};
const iso=d=>d.toISOString().slice(0,10);async function get(url){const r=await fetch(url);if(!r.ok)throw Error('source');const x=await r.json();if(!x)throw Error('data');return x}
async function weather(){const end=new Date();end.setUTCDate(end.getUTCDate()-1);const start=new Date(end);start.setUTCDate(start.getUTCDate()-6);return get(`https://api.open-meteo.com/v1/forecast?latitude=${LAT}&longitude=${LON}&daily=precipitation_sum&timezone=Europe%2FMadrid&start_date=${iso(start)}&end_date=${iso(end)}`)}
async function flood(){return get(`https://flood-api.open-meteo.com/v1/flood?latitude=${LAT}&longitude=${LON}&daily=river_discharge&past_days=7&forecast_days=1&timezone=Europe%2FMadrid`)}
// Public EDO adapter; its map/download service may evolve, so malformed responses fail safely.
async function drought(){const x=await get(`https://edo.jrc.ec.europa.eu/edov2/php/index.php/api/edodata?lat=${LAT}&lon=${LON}`);const n=Number(x.droughtIndex??x.cdi??x.CDI??x.value);if(!Number.isFinite(n))throw Error('drought');return n}
function assess(rain,drought,flow){let s=drought>=3?4:drought>=2?3:drought>=1?1:0;s+=rain<5?3:rain<15?2:rain<30?1:0;s+=flow===null?0:flow<10?3:flow<25?2:flow<50?1:0;return{score:s,level:s<=2?'Normal':s<=4?'Watch':s<=7?'Alert':'Emergency'}}
function bars(values){$('bars').innerHTML=values.map((v,i)=>`<div class="bar-col"><span>${v.toFixed(1)}</span><i class="bar" style="height:${Math.min(100,Math.max(3,v*7))}%"></i><span>D${i+1}</span></div>`).join('')}
async function refresh(){ $('refresh').disabled=true;$('warning').hidden=true;$('risk').className='risk loading';$('risk').textContent='Loading';try{const[w,f,d]=await Promise.all([weather(),flood(),drought()]);const vals=(w.daily?.precipitation_sum||[]).map(Number);if(vals.length<7||vals.some(Number.isNaN))throw Error('weather data');const fs=(f.daily?.river_discharge||[]).map(Number).filter(Number.isFinite),flow=fs.length?fs[fs.length-1]:null,total=vals.reduce((a,b)=>a+b,0),a=assess(total,d,flow);$('rain').textContent=total.toFixed(1)+' mm';$('drought').textContent=d.toFixed(2);$('flow').textContent=flow===null?'—':flow.toFixed(1);$('score').textContent=a.score;$('risk').textContent=a.level;$('risk').className='risk '+a.level.toLowerCase();$('action').textContent=actions[a.level];$('reason').textContent=`Based on ${total.toFixed(1)} mm rainfall, EDO drought index ${d.toFixed(2)}, and ${flow===null?'no available':flow.toFixed(1)+' m³/s'} discharge proxy.`;bars(vals);const now=new Date().toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'});$('updated').textContent='Updated '+now;$('footer-update').textContent=now}catch(e){$('warning').hidden=false;$('risk').textContent='Unavailable';$('risk').className='risk loading';$('score').textContent='—';$('action').textContent='Risk assessment paused until public data sources recover.';$('reason').textContent='One or more required external sources returned bad or unavailable data.'}finally{$('refresh').disabled=false}}$('refresh').addEventListener('click',refresh);refresh();
